### ISSUE TITLE
Login Fail to DN

### ISSUE THREAD

**Issue by maxswjeon** [dnknth/ldap-ui#13]
If failed with uid authentication, try login with username as dn. This is an option that phpLDAPadmin uses and many servers make users without uid for admin account. (ex. [osixia/docker-openldap](https://github.com/osixia/docker-openldap) makes `cn=admin,dc=example,dc=org` account for default administration)

**Comment by dnknth** [comment]
Hello @maxswjeon,

You can use the `BIND_DN` in [settings.py](../settings.py) for an administrative account. If that does not solve the problem, please explain what is needed. Do you mean a DN pattern like `cn=%s,dc=example,dc=org` where `%s` is substituted with the user name?

**Comment by maxswjeon** [comment]
No, it's not `BIND_DN` problem, it's the login problem.
Initial users in (osixia/docker-ldap)[https://github.com/osixia/docker-openldap] does not have uid attribute, just cn attributes. In phpLDAPadmin, even when login with uid is enabled, they serve `fallback_dn` option to fall back to dn match when failed with uid login  If enabled, I can login with username: `cn=admin,dc=example,dc=org` and password. 

I suggeest a option like `fallback_dn` in phpLDAPadmin

**Comment by dnknth** [comment]
Hello @maxswjeon,

Currently there are several ways to achieve a login:

1. Search by some attribute.  By [default](../blob/d0a1431dda327d44351e47b8e6fc43444f62abdd/settings.py#L15), this is `uid`, which can be overridden by the environment variable `LOGIN_ATTR=cn`.
3. If the environment variable `BIND_PATTERN` is set, then no search is performed. Login with a full DN can be configured with `BIND_PATTERN=%s`, which allows to login as user `cn=admin,dc=example,dc=org`. If a partial DN like `%s,dc=example,dc=org` is configured, the corresponding login would be `cn=admin`. If a specific CNs pattern like `cn=%s,dc=example,dc=org` is configured, the login name is just `admin`.
4. If security is no concern, then a fixed `BIND_DN` and `BIND_PASSWORD` can be set in the environment. This is for demo purposes only, and probably a very bad idea if access to the UI is not restricted by other means.

Of course, you could always add `objectClass=simpleSecurityObject` and `uid=admin` to `cn=admin,dc=example,dc=org` via `ldapmodify(1)`, which makes it accessible for the normal user search by `uid`.

If none of these fit your needs, please explain why.

**Comment by dnknth** [comment]
Hello @maxswjeon,

Can we close this issue?

**Comment by maxswjeon** [comment]
Thanks.
