### ISSUE TITLE
[JS] issue with DN parsing

### ISSUE THREAD

**Issue by GilZm** [dnknth/ldap-ui#14]
When base dn is single leveled (so to speak), the app.js fail to render the tree (no exception, but an infinite loop).

For example, I setup a demo ldap which base dn is 'dc=local'. This seem to bother when app.parent(dn) is called within 'for' loops (https://github.com/dnknth/ldap-ui/blob/c150443f7f00c9550a473bcf1d4e210d811cd7f0/static/app.js#L218 and https://github.com/dnknth/ldap-ui/blob/c150443f7f00c9550a473bcf1d4e210d811cd7f0/static/app.js#L1003).

This screw up the browser and I had a lot of pain attempting to narrow down the issue.

**Comment by dnknth** [comment]
Hello @GilZm, thanks for analysing this corner case. I pushed a fix that should solve the issue. Please try it out!

**Comment by GilZm** [comment]
successfully tested !!

many thanks for you help
