### ISSUE TITLE
[request] gid auto-increment

### ISSUE THREAD

**Issue by blasphemite** [dnknth/ldap-ui#15]
I noticed when creating posixGroups, the gids are not automatically populated and can actually be duplicated. I'm wondering, would it be possible to set a base gid or something, then have each subsequently created gid auto-increment? Or at least a warning on the New Entry prompt stating that the chosen gid already exists.

Love the project, by the way -- happy to hopefully move away from phpLDAPadmin!

**Comment by dnknth** [comment]
Hello @blasphemite, 

Right now, the UI does not offer any business logic, i.e. the abstraction level is pretty much like LDIF changes, but a bit more colourful. Having said that, it would be useful if the UI could display the minimum and maximum values that are already used for attributes like `gid` of a `posixGroup`, or `uid` for `posixAccount`. 

The user would still need to add one to the maximum and type it in for new entries, or manually check for any gaps in the range, if they want to re-use them.

Would that be helpful enough?

**Comment by blasphemite** [comment]
I think it would, yes.

**Comment by dnknth** [comment]
Hello @blasphemite,

Support for `uidNumber` and `gidNumber` was added in b609021. It includes auto-increment on empty fields. However, this might produce surprising (and wrong) results, for instance in the `gidNumber` for a new `posixAccount`. For that reason, the automatically supplied values are marked red.

You can try it locally with the latest `master` version. If you use Docker, you'd need to build the image first, I have not pushed it yet to Dockerhub. See the `Makefile` on how to do it. I'll test the feature a little bit more before updating the Docker images.

Cheers, dnknth

**Comment by dnknth** [comment]
Updated Docker image

**Comment by dnknth** [comment]
Hello @blasphemite, can we close this now?
