### ISSUE TITLE
Username & Password example

### ISSUE THREAD

**Issue by oktayaa** [dnknth/ldap-ui#2]
Can you please provide a bit info on what the username password looks like? Is it 'uid' based or does it require a full uid=user,dc=example,dc=com mapping?

I am getting no feedback after I enter the user and password that they are wrong. It's just a blank page with a header and a little box on the top left corner which doesn't respond.

**Comment by dnknth** [comment]
The default attribute for user name lookup is indeed `uid`. You can define another attribute in the `LOGIN_ATTR` environment variable. The app searches the user name in the subtree given by  `BASE_DN` and expects a unique result (or none). 

The behaviour you described could be caused by a search failure, either due to an invalid `BASE_DN` or because the search yields more than a single result. Did you check the container log for errors?

**Comment by oktayaa** [comment]
Nothing in docker logs. 

But my ldap logs show 

> Mar 26 18:35:56 virt01 slapd[2332]: conn=6638 op=0 SEARCH RESULT tag=101 err=53 nentries=0 text=authentication required

Is there somewhere to set an actual bind dn ? My server does not accept anonymous noauth binds.

**Comment by dnknth** [comment]
Added support for `BIND_DN` and `BIND_PASSWORD` environment variables. If these are set, the UI will bypass authentication and must be secured by other means.

The Docker image should rebuild automatically in a few minutes.

**Comment by oktayaa** [comment]
Thank you!

**Comment by dnknth** [comment]
Does it work now?

**Comment by oktayaa** [comment]
I was able to log in and see my ldap tree. Didn't have time to test much further. But I did NOT see a place to create a new users.

I've also gone back to reading up on LDAP and talked to some people on IRC to figure out whether I should have anonymous binds disabled at all. The answer seems to be no. So maybe I won't need to hard code the bind_dn after all.

However I noticed that this app can benefit from users being able to specify the search filter. I mounted the /app folder on docker because I was planning to do a few tests but I ran out of time. (2 am here)

I will get back to you about that when I get a chance to look at it.

**Comment by oktayaa** [comment]
OK. I was able to log in with bind_dn in the config file. As I've said before I can't figure out where to "ADD" things. I can modify existing records. Also I do see the interface for adding Attributes, but I haven't tested it.

Another thing. (I am informally letting you know instead of creating an issue) After just a few gui operations the gui first freezes then crashes the tab. This is with vivaldi (chromium based) running docker container from yesterday. There's nothing in the logs. If there's a way to increase log verbosity I'd be happy to check it out and let you know what I get.

Cheers.

**Comment by dnknth** [comment]
Have you seen the drop-down menu in the editor title?

No point opening an issue on your browser crashes. I have tested the app with Firefox (Mac, Windows, Ubuntu), Chrome (Windows), Safari (Mac), Edge and IE and will not spend any time on browsers with insignificant market share (other than closing such requests as `wontfix`)

**Comment by oktayaa** [comment]
No worries. I wasn't expecting a fix for it. 

I have a the username (clicking it doens't do anything), and a schema and import menu items.

**Comment by dnknth** [comment]
![Bildschirmfoto 2020-03-27 um 17 28 24](https://user-images.githubusercontent.com/41536869/77778120-d5824380-7050-11ea-9c20-391ed1292400.png)

**Comment by oktayaa** [comment]
Thank you!
