### ISSUE TITLE
Demo docker image does not connect

### ISSUE THREAD

**Issue by ben-ihelputech** [dnknth/ldap-ui#22]
# Localhost:5000 does not connect to the LDAP container
I tried running docker-demo/start.sh from the cloned folder. Docker compose was successful in bringing the images up, but when I launched the web page on local host 5000, it was not able to connect.  
I figured that I may have an issue with my local install so I created a new ubuntu vm with the latest version of docker and docker compose installed on it and I still ran into the same problem. (screen shot below)
![Screenshot from 2021-12-22 09-05-46](https://user-images.githubusercontent.com/50592898/147113710-b110b453-90f4-4d32-bc92-e2cb81e0d5fd.png)

**Comment by dnknth** [comment]
Hello @ben-ihelputech, sorry for the tardy reply.

First could you check whether the `ldap` service comes up as expected with `docker-compose ps`?
If it keeps restarting, please get the logs of the `ldap` service with `docker-compose logs ldap` and paste the last round as a comment.

Thanks!

**Comment by ben-ihelputech** [comment]
I do see that the ldap service is restarting.
```
ben@ldap-ui:~/Documents/ldap-ui$ sudo docker-compose ps
        Name                       Command                 State               Ports          
----------------------------------------------------------------------------------------------
docker-demo_ldap-ui_1   /usr/bin/hypercorn -b 0.0. ...   Up           127.0.0.1:5000->5000/tcp
docker-demo_ldap_1      /start.sh                        Restarting
```

Attached is the log file I generated with `docker-compose logs ldap > docker-demo.log`
[docker-demo.log](https://github.com/dnknth/ldap-ui/files/7816488/docker-demo.log)

**Comment by dnknth** [comment]
There seems to be an [issue](mwaeckerlin/openldap#23) in the LDAP container that is used for the demo.

**Comment by ben-ihelputech** [comment]
I will have to do more testing in the future. I will close the issue for now.

**Comment by dnknth** [comment]
Since the upstream bug is still open, I've pushed a corrected version `dnknth/openldap` to Docker hub and updated `docker-compose.yml` accordingly. Will revert this when the original issue is solved.
