### ISSUE TITLE
⛔ Can't contact LDAP server: Socket not connected

### ISSUE THREAD

**Issue by hxvxt2** [dnknth/ldap-ui#3]
Hello @dnknth 

I am able to log in on the app but the schema isn't loading. Nothing happens when I try to click on any of the UI components. I also tried to load some users from an LDIF file but got the same error. 

What am I missing?

Regards

**Comment by dnknth** [comment]
Could you please check the browser console and the Python app log for errors and send them?

**Comment by hxvxt2** [comment]
I am running the docker image so not sure where I can find the Python app log, but here is the console logs as you asked...

```
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map
DevTools failed to parse SourceMap: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/contentscript.js.map
DevTools failed to parse SourceMap: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/inpage.js.map
VM509:1 GET http://localhost:5000/api/whoami 500
(anonymous) @ VM509:1
(anonymous) @ app.js:42
request @ app.js:15
created @ app.js:130
He @ vue.min.js:6
Yt @ vue.min.js:6
t._init @ vue.min.js:6
wn @ vue.min.js:6
(anonymous) @ app.js:47
VM509:1 GET http://localhost:5000/api/tree/base 500
(anonymous) @ VM509:1
(anonymous) @ app.js:42
request @ app.js:15
reload @ app.js:184
created @ app.js:135
He @ vue.min.js:6
Yt @ vue.min.js:6
t._init @ vue.min.js:6
wn @ vue.min.js:6
(anonymous) @ app.js:47
VM509:1 GET http://localhost:5000/api/schema 500
(anonymous) @ VM509:1
(anonymous) @ app.js:42
request @ app.js:15
created @ app.js:138
He @ vue.min.js:6
Yt @ vue.min.js:6
t._init @ vue.min.js:6
wn @ vue.min.js:6
(anonymous) @ app.js:47
localhost/:1 Uncaught (in promise) XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
Promise.then (async)
created @ app.js:130
He @ vue.min.js:6
Yt @ vue.min.js:6
t._init @ vue.min.js:6
wn @ vue.min.js:6
(anonymous) @ app.js:47
localhost/:1 Uncaught (in promise) XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
Promise.then (async)
reload @ app.js:184
created @ app.js:135
He @ vue.min.js:6
Yt @ vue.min.js:6
t._init @ vue.min.js:6
wn @ vue.min.js:6
(anonymous) @ app.js:47
localhost/:1 Uncaught (in promise) XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
Promise.then (async)
created @ app.js:138
He @ vue.min.js:6
Yt @ vue.min.js:6
t._init @ vue.min.js:6
wn @ vue.min.js:6
(anonymous) @ app.js:47
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map
DevTools failed to parse SourceMap: chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/atoms.js.map
DevTools failed to parse SourceMap: chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/polyfills.js.map
DevTools failed to parse SourceMap: chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/escape.js.map
DevTools failed to parse SourceMap: chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/playback.js.map
DevTools failed to parse SourceMap: chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/record.js.map
localhost/:1 Error while trying to use the following icon from the Manifest: http://localhost:5000/static/icons/64px.png (Resource size is not correct - typo in the Manifest?)

```

**Comment by dnknth** [comment]
Please have a look at the output of `docker logs CONTAINER_NAME` and send anything that looks suspicious.

**Comment by hxvxt2** [comment]
Well, that gives me nothing, just to be double sure I pulled a fresh image and ran a new container. Here is what I did:-

`❯ docker run -it -p 5000:5000 -e LDAP_URL=ldap://localhost:389 -e BASE_DN=dc=grofers,dc=local dnknth/ldap-ui`

> Unable to find image 'dnknth/ldap-ui:latest' locally
> latest: Pulling from dnknth/ldap-ui
> aad63a933944: Already exists
> 48eb215db2c7: Pull complete
> 3d847da3890a: Pull complete
> Digest: sha256:68b648230374e43802313da2526fbc61e4bf1c298def16645c793c9c3f45dd9c
> Status: Downloaded newer image for dnknth/ldap-ui:latest
> Running on 0.0.0.0:5000 over http (CTRL + C to quit)

Then I tried to run docker logs

`❯ docker logs 1f4a493d69ce`
>Running on 0.0.0.0:5000 over http (CTRL + C to quit)

**Comment by dnknth** [comment]
Strange, because the JS logs show errors. There should be exceptions in the Docker log. However, the likely reason is a mistake in the `LDAP_URL`. You set it to `localhost`, so the UI expects an LDAP server in the container but there is none. Try `LDAP_URL=ldap://docker.host.internal` if the LDAP server runs on the same machine as Docker.
See https://stackoverflow.com/a/24326540 for an explanation.

**Comment by hxvxt2** [comment]
I am able to log in (i vaguely remember logging in) on the `ldap-ui` app using my LDAP admin creds...so the app is probably able to detect my LDAP server? It's only after the login I am not able to see schema.

I have got something from the network tab of dev tools too...if that helps

| Request link                     | Request Header | Response Header | Response |
| ---------------------------------| -------------  | --------------- | -------- |
| http://localhost:5000/api/whoami | GET /api/whoami HTTP/1.1<br>Host: localhost:5000<br>Connection: keep-alive<br>Pragma: no-cache<br>Cache-Control: no-cache<br>Authorization: Basic YWRtaW46YWRtaW4=<br>User-Agent: Mozilla/5.0 (Macintosh;Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36<br>Sec-Fetch-Dest: empty<br>Accept: */*<br>Sec-Fetch-Site: same-origin<br>Sec-Fetch-Mode: cors<br>Referer: http://localhost:5000/<br>Accept-Encoding: gzip, deflate,<br>Accept-Language: en-IN,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,hi;q=0.6<br>Cookie: FusionDirectory=eb20bfa9418f35e0e5798a31bdb34c0b<br> | HTTP/1.1 500<br>content-type: text/html<br>content-length: 126<br>date: Fri, 24 Apr 2020 06:31:29 GMT<br>server: hypercorn-h11<br> | <!doctype html><br><title>500 Can't contact LDAP server</title><br><h>Can't contact LDAP server</h><br>Socket not connected |
| http://localhost:5000/api/schema | GET /api/schema HTTP/1.1<br>Host: localhost:5000<br>Connection: keep-alive<br>Pragma: no-cache<br>Cache-Control: no-cache<br>Authorization: Basic YWRtaW46YWRtaW4=<br>User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36<br>Sec-Fetch-Dest: empty<br>Accept: */*<br>Sec-Fetch-Site: same-origin<br>Sec-Fetch-Mode: cors<br>Referer: http://localhost:5000/<br>Accept-Encoding: gzip, deflate, br<br>Accept-Language: en-IN,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,hi;q=0.6<br>Cookie: FusionDirectory=eb20bfa9418f35e0e5798a31bdb34c0b<br> | HTTP/1.1 500<br>content-type: text/html<br>content-length: 126<br>date: Fri, 24 Apr 2020 06:31:29 GMT<br>server: hypercorn-h11<br> | <!doctype html><br><title>500 Can't contact LDAP server</title><br><h>Can't contact LDAP server</h><br>Socket not connected |
| http://localhost:5000/api/tree/base | GET /api/tree/base HTTP/1.1<br>Host: localhost:5000<br>Connection: keep-alive<br>Pragma: no-cache<br>Cache-Control: no-cache<br>Authorization: Basic YWRtaW46YWRtaW4=<br>User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36<br>Sec-Fetch-Dest: empty<br>Accept: */*<br>Sec-Fetch-Site: same-origin<br>Sec-Fetch-Mode: cors<br>Referer: http://localhost:5000/<br>Accept-Encoding: gzip, deflate, br<br>Accept-Language: en-IN,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,hi;q=0.6<br>Cookie: FusionDirectory=eb20bfa9418f35e0e5798a31bdb34c0b<br> | HTTP/1.1 500<br>content-type: text/html<br>content-length: 126<br>date: Fri, 24 Apr 2020 06:31:29 GMT<br>server: hypercorn-h11 | <!doctype html><br><title>500 Can't contact LDAP server</title><br><h>Can't contact LDAP server</h><br>Socket not connected |

**Comment by hxvxt2** [comment]
I see the UI implements Basic Auth, so probably the creds I entered don't even matter. I'll think it's the network issue between my LDAP docker and UI docker as you mentioned. 

I'll try running them on same network. Perhaps the app could be more little more descriptive if the LDAP bing wasn't successful?

**Comment by dnknth** [comment]
All requests come back with an `internal server error` (500). I agree that this should trigger some error message in the UI.

Let's assume that you run the LDAP server a container named `ldap`. If it is in the same network as the UI, then I suppose that `LDAP_URL=ldap://ldap` should work.

**Comment by hxvxt2** [comment]
Thanks for your help @dnknth got it fixed.
I first ran
`docker inspect <my LDAP container ID> | grep -i network` and found out it was running on `"NetworkMode": "services"`

Then 
`docker inspect bc317aa12531|grep -i IPAddress` and got the IP of the LDAP container

Ran UI on the same network and used the LDAP container's IP
`docker run -it --network="services" -p 5000:5000 -e LDAP_URL=ldap://xxx.xx.x.x:389 -e BASE_DN=dc=xxx,dc=local dnknth/ldap-ui`
