### ISSUE TITLE
What means hypercorn: Command not found ?

### ISSUE THREAD

**Issue by evheniu** [dnknth/ldap-ui#32]
root@ubuntu-server:/home/user/ldap-ui# make run
.venv3/bin/hypercorn -b 0.0.0.0:5000 --access-logfile - app:app
make: .venv3/bin/hypercorn: Command not found
make: *** [Makefile:11: run] Error 127

I install hypercorn via pip / pip3 and this didn't works.

**Comment by dnknth** [comment]
Are you in a virtualenv and did you activate it?

**Comment by evheniu** [comment]
You mean before running "make run" I need create venv ?

I was create venv via - python3 -m venv venv and activate it but that not help:

I have same error

(venv) root@ubuntu-server:/home/user/ldap-ui# make run
.venv3/bin/hypercorn -b 0.0.0.0:5000 --access-logfile - app:app
make: .venv3/bin/hypercorn: Command not found
make: *** [Makefile:11: run] Error 127

**Comment by dnknth** [comment]
Have you solved it and if so, how?
