### ISSUE TITLE
GET https://unpkg.com/vue@3.2.37/dist/vue.min.js net::ERR_ABORTED 404

### ISSUE THREAD

**Issue by Whyupup** [dnknth/ldap-ui#33]
Why do I return this when I visit a web page: 'GET https://unpkg.com/vue@3.2.37/dist/vue.min.js net::ERR_ABORTED 404' ,and there is no login interface,This is the page when I visited
![image](https://user-images.githubusercontent.com/96057459/187112030-d959c92d-51c6-42e9-8eb8-c2dbee36a0e7.png)

**Comment by dnknth** [comment]
This issue is not reproducible on my end. Please provide instructions what you tried, and how to trigger the error that you have observed.

**Comment by Whyupup** [comment]
I have solved this problem,Maybe it's because I used docker images
