### ISSUE TITLE
please re-phrase in the readme..

### ISSUE THREAD

**Issue by dkalog** [dnknth/ldap-ui#35]
Instead of ..

If a partial DN like BIND_PATTERN=%s,dc=example,dc=org is configured, the corresponding login would be cn=admin. If a specific pattern like BIND_PATTERN=cn=%s,dc=example,dc=org is configured, the login name is just admin.

replace with

If a partial DN like BIND_PATTERN=%s,dc=example,dc=org is configured, the corresponding login would be admin. If a specific pattern like BIND_PATTERN=cn=%s,dc=example,dc=org is configured, the login name is just cn=admin.

**Comment by dnknth** [comment]
The original wording is correct, and the proposed solution is not. You can easily test it with the Flintstones demo in the `docker-demo` directory.
