### ISSUE TITLE
Add some icon for groupOfURLs

### ISSUE THREAD

**Issue by Samonitari** [dnknth/ldap-ui#38]
Thanks for the project!

Small, cosmetic issue:
The quasi-group object `groupOfURLs` does not get a group icon.
Either:

- Use the same icon as for "regular groups" (`groupOfNames`)
- Differentiated from "regular groups", as these are dynamic ones which return a set search querie's result

**Comment by dnknth** [comment]
Added the regular group icon, if you find something better [here](https://fontawesome.com/v4/icons/), we can change it.
Docker image is also updated.

**Comment by dnknth** [comment]
Hi @Samonitari, blase close this issue when happy. Otherwise, please let me know what's missing.

**Comment by Samonitari** [comment]
Thank you very much!
And sorry for the delay, in the last weeks (and a few more) I was into consolidating two servers into one.

On the bright side, yesterday I got into setting up ldap-ui on the new server, and the icon is loaded correctly!
I glanced at the icons, but did not find a more appropriate one.
