### ISSUE TITLE
How to change BIND_PATTERN based on subdomain

### ISSUE THREAD

**Issue by Samonitari** [dnknth/ldap-ui#39]
Hi again!

This is more of a question than an issue.

I am hosting a few domains' stuff (email, etc.) on a server, and under LDAP root, there are domain object subtrees for each, with every one of them containing users, groups, etc.
I have a group for every hosted-domain like `uid=ldapadmins,ou=groups,dc=hosted-domain1,dc=myhosting` with member(s) from the `ou=people,dc=hosted-domain1,dc=myhosting`
With some ACL regex-magix, I made it so that every `ldapadmins` group's members can manage their respective domain subtree, but only that (see \*)
By also adding `to dn.one="" ... read` access for them, they can log in, see the root `dc=myhosting`, and manage their own subtree with LDAP-UI, with a single `BASE_DN` - as the latter must be set to run the app-service.

My mostly cosmetic issue:
My site-admins (who can be not so technical) can login with the verbose `uid=siteadmin1,ou=people,dc=hosted-domain1`, thanks to `BIND_PATTERN=%s,dc=myhosting`.
Could I do something to ease their login (like erect an LDAP-UI page for each subdomain with the reverse-proxy, and each having their own request rewrites)? Unfortunately I am not versed enough to find out what/how to rewrite...

Thanks for the help!

\* For the curious:
`{2}to dn.regex="(.+,)?(dc=[a-z-]+\.[a-z]+,dc=myhosting)$" by group.expand="uid=ldapadmins,ou=groups,$2" manage by dn.regex="cn=[a-z]+,ou=services,$2" read by * break`
I have domain specific `services` (like nextcloud) that can read their own domain's subtrees, hence the read access...

**Comment by dnknth** [comment]
Hello @Samonitari 

I have similar Regex magic in place, but you beat me 👍🏻 
How comfortable are you with fiddling in Python?

Basically, it happens [here](https://github.com/dnknth/ldap-ui/blob/master/app.py#L45).
Applying a BIND_DN is just a way of determining a user DN from some given string.
It would be easy to define a user-defined function in [settings.py](https://github.com/dnknth/ldap-ui/blob/master/settings.py) that does the same thing a bit differently.

I could generalise the logic in the app, but this means that you'd need to roll your own image
with modifications in the settings (if using Docker).

Using environment variables to enable your special case seems a bit over the top,
unless you can suggest an easy solution.

**Comment by Samonitari** [comment]
Thanks for the pointers!

> I have similar Regex magic in place, but you beat me 👍🏻
I trained my regex-fu in (neo)vim 😆 

> How comfortable are you with fiddling in Python?
I'd say moderately, the problem is rather the 'web stuff' here...

It is not perfectly clear to me how to solve it that could make it to your master.
If I read it correctly, I could get the (sub)domain URI from `request` and use it as a part of dn.

> ... you'd need to roll your own image with modifications in the settings (if using Docker)
No problem, I run python stuff in virtualenv started by a properly sand-boxed systemd unit...
Don't let me get started with my pet-peeve: "Docker-over-usage" 😅 

I'll think and tinker a bit based on you pointer, maybe I'll come up with something that not 'Just Works'™️  but also can be upstreamed.

**Comment by dnknth** [comment]
Hello @Samonitari,

BIND_PATTERN is just a special way of getting a DN from some given user name in the request.

I moved the DN / password extraction via environment variables into `settings.py` to simplify customisation.
Hope that helps.

**Comment by dnknth** [comment]
Hello @Samonitari, I'd appreciate a comment before closing this issue.

**Comment by dnknth** [comment]
Nobody out there, closing it. Feel free to re-open with comments.
