### ISSUE TITLE
ldaps with a self signed cert

### ISSUE THREAD

**Issue by EduardoOliveira** [dnknth/ldap-ui#4]
Hi
Our ldap server uses a self signed cert and I get this message after trying to authenticate:
```Can't contact LDAP server: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed (self signed certificate in certificate chain) ```
Is there a way to add a trusted cert or to disable the validation?

Thank you

**Comment by dnknth** [comment]
The certificate validation is handled in OpenLdap's `libldap` which in turn uses some SSL library (GnuTLS on Debian).
So you would need to add your self-signed cert as a trusted certificate for the machine where the UI runs. Personally, I do not know how that works for self-signed certificates, and there are probably differences between Linux distributions.

**Comment by EduardoOliveira** [comment]
I've dug up some more information on how the server is configured.
I've got the CA, I'll try to extend the image and add the CA at build time.
Is that a path that you would recommend?

Thank you

**Comment by dnknth** [comment]
That's probably the best approach. However, it might be necessary to add some SSL related packages like `ca-certificates`. If you get it working, please share how you did it.

**Comment by EduardoOliveira** [comment]
Hi,
I've extended the image and added the cert but I get the following message on the UI:
`Can't contact LDAP server: TLS: hostname does not match CN in peer certificate`

which is different from the message with the original image:
`Can't contact LDAP server: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed (self signed certificate in certificate chain)`

Is there a way to enable a verbose output to the stdout? the output stream is completely empty even with the errors.


Thank you

**Comment by dnknth** [comment]
Hello,

Are you using the correct server name in the UI configuration? Does the cert contain the name in the SubjectAlternateName (SAN) extension?

It is possible to also add logging to stderr, but you would see exactly the same message there.

**Comment by EduardoOliveira** [comment]
I got to connect to the ldap, it's asking for the user/pw, failing on that but ons step at a time.
As for the certs

Dockerfile
```
FROM dnknth/ldap-ui

RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*

COPY TRALALA.crt /usr/local/share/ca-certificates/TRALALA.crt
```

docker-compose.yml
```
ldap:
#  image:  dnknth/ldap-ui
  build: .
  environment:
    LDAP_URL: ldaps://weee.host/
    BASE_DN: dc=weee,dc=com
  extra_hosts:
     - "weee.host:192.168.333.444"
```

for the cert to work the host needs to mach the issuer CN, since I don't have DNS configured I've added it thru the extra_hosts which internally adds it to the /etc/hosts of the container

I would give this one as closed.
If I may be of any help just let me know

Thank you for the free sotfware
