### ISSUE TITLE
add multiarch support

### ISSUE THREAD

**Issue by 1gnatov** [dnknth/ldap-ui#41]
Hi! 

docker image is not working at M1 minikube(on docker).

Can you please add multiarch build? https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by 1gnatov** [comment]
and push it to docker hub

**Comment by RicardoJeronimo** [comment]
Same thing happens on an arm64 Raspberry Pi 4.

Thanks!

**Comment by dnknth** [comment]
Rebuild it on a Raspi4 and uploaded a [multiarch image](https://hub.docker.com/r/dnknth/ldap-ui/tags) for `amd65` and `arm64/v8` to Docker Hub. Please be aware that only the `ldap-ui` image is available for `arm64`, and not the `ldap-demo` image referenced in [docker-compose.yml](/dnknth/ldap-ui/blob/master/docker-compose.yml), so you'll need to bring your own LDAP server.

Please leave a comment whether this works for you.

**Comment by RicardoJeronimo** [comment]
Hey, @dnknth, the image worked perfectly on arm64, thank you!
