### ISSUE TITLE
We're sorry but JavaScript is required. Please enable it to continue.

### ISSUE THREAD

**Issue by whg517** [dnknth/ldap-ui#47]
env:

- macos 14.1.1
- edge 119.0.2151.97 (arm64)
- Docker Desktop 4.25.2 (129061)

### desc

when i access webui, nothing to show. I fond `We're sorry but JavaScript is required. Please enable it to continue.` with browser debug. And edge already enabled JavaScript.

```bash
docker run --rm -p 5000:5000 \
  -e BIND_PATTERN=cn=%s,ou=users,DC=ldap,DC=goauthentik,DC=io \
  -e LOGIN_ATTR=cn \
  -e LDAP_URL=ldap://192.168.71.98:3389/ \
  -e BASE_DN=DC=ldap,DC=goauthentik,DC=io dnknth/ldap-ui
```

**Comment by whg517** [comment]
@dnknth Yes, chrome tried that too. This includes using the gust pattern.

**Comment by dnknth** [comment]
Hello @whg517, do you mean that you tried Chrome? If so, did it work or did you get the same error?

**Comment by whg517** [comment]
@dnknth yes. Just like I said before. In addition, thank you for your prompt reply and patience.

Now I've discovered lldap, a lightweight LDAP tool, through the community. I choose to choose to use it. 

So I'll close this issue later.
