### ISSUE TITLE
Unable to logout of UI

### ISSUE THREAD

**Issue by zer0ish** [dnknth/ldap-ui#48]
Hello,

I just started playing with this on unraid docker with openldap, and was wondering if I there could be a Logout function for the web gui.
Not sure if it's there and I just can't see it, but I don't like the idea of not being logged out when the tab is closed.

**Comment by dnknth** [comment]
No, there is none. As the ReadMe states, it is using HTTP Basic auth. The browser stays logged in until it (completely) exits. Should you disagree with this, please look for a browser extension to clear Basic auth credentials.
