### ISSUE TITLE
Attributes from custom schemas are not editable anymore

### ISSUE THREAD

**Issue by adrianparilli** [dnknth/ldap-ui#50]
Hello. Thank you very much for your cool app. I find it particularly useful since it shows all fields of a given schema, regardless if is custom made, as it's the case for me.

After upgrading to the latest docker image, I've found boolean attributes are not editable anymore. 

E.g: I create a new LDAP group, adding RDN, objectClass and per schema defined attributes. Everything looks ok, but when comes to create/edit a boolean attribute, the field is not writable.

Also, checking other entries (created or edited with past versions of this same front end, the previously editable attribute is not modifiable anymore.

I use a custom schema for different purposes. The kind of boolean attribute (actually, different attribute names but same syntax) is like this:

attributetype ( 1.3.6.1.4.1.xxxxx.1.1.1.1.1
    NAME 'x-accountEnabled'
    DESC 'Defines if a given user is active (TRUE or FALSE)'
    EQUALITY booleanMatch
    SYNTAX 1.3.6.1.4.1.1466.115.121.1.7
    SINGLE-VALUE )

Right now, all tested builds (amd64) have the same issue. I know in the past this wasn't the case.

Tested with Mozilla Firefox 122.0 and Brave v1.62.156 (Chromium 121.0.6167.139)

I would appreciate your feedback...

**Comment by dnknth** [comment]
Will investigate, but please allow some time as I need to extend my test schema first with boolean attributes.

**Comment by dnknth** [comment]
Hello @adrianparilli,

Tried it with the `ppolicy` schema which luckily contains some boolean attributes. 

<img width="617" alt="boolean" src="https://github.com/dnknth/ldap-ui/assets/41536869/b94d1957-6422-46d6-af9f-de9b6d835e85">

At least over here, the UI accepts the values `TRUE` and `FALSE` but nothing else (with an LDAP error message). Which exact Docker image did you try? Please state the architecture and image hash so I can try to narrow it down.

**Comment by adrianparilli** [comment]
Hi @dnknth, thank you for your reply.

I've changed the subject for more clarity about this issue.

(Sorry about bothering you to the extent of have to look for boolean stuff! Certainly, only can be 'TRUE' or 'FALSE', and all in caps, otherwise LDAP server will return an error and won't accept the input. This is pretty normal.)

I noticed first custom boolean attributes wasn't being editable anymore, but after a thoughtful check, the problem isn't limited to these, but to ANY custom attribute present on LDAP server, as part of a custom schema.

By the way, backend is OpenLDAP 2.6.7, Alpine Linux (dockerized)

Since the latest docker image upgrade:

- Custom attributes, although still shown correctly and seem able to be added, at the time to actually write on the field box, nothing happens, therefore can't be saved.
- Already existing custom attributes still appear, but can't be neither edited, nor removed.
- By the other hand, any other attribute present in a 'standard' schema in use (such as system, core, cosine, and as you could verify in your search: inetOrgPerson) can be added, edited and deleted normally.

All the mentioned custom attributes start with 'x-' and the schema follows the recommendations at [OpenLDAP's documentation.](https://www.openldap.org/doc/admin26/schema.html#Naming%20Elements)

Perhaps, is the issue something related with changed dependencies and now they only work with standard, well-known attributes?

I hope that isn't the case. Honestly, the best of this UI it's precisely that doesn't force one to get married with strict schemas and instead, it limits to allow free management (as long this is permitted by inherent LDAP tree's nature.)

I'm using amd64 version, and `docker images --digest` returns this:
dnknth/ldap-ui latest
sha256:2f6f2b8faff34b6eb5621260c5109a96b922ddb2622a8272bd841b9afaace1f1
4dbff2d68574 <== digest
5 months ago

Fortunately, I still have local images into another host from past deployments, and using the latest one working, in the meanwhile.

(Latest working one I have)
sha256:68213ee2968f603a6c0c51ee0b2d1f68a3993be602fb708446457ac5cf09fe8c
24adb13547ba
6 months ago

(Another older one, also working)
sha256:17e13ec6dca3662b8867d46497fe4fd8d650c87dc747d5673cf00f381426c731
332d58f5c6a8
7 months ago

Good to point is that these old images aren't in docker hub anymore.
I also tried to build from source, but I get this error:

```
error: externally-managed-environment

× This environment is externally managed
╰─> 
    The system-wide python installation should be maintained using the system
    package manager (apk) only.
    
    If the package in question is not packaged already (and hence installable via
    "apk add py3-somepackage"), please consider installing it inside a virtual
    environment, e.g.:
    
    python3 -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage
    
    To exit the virtual environment, run:
    
    deactivate
    
    The virtual environment is not deleted, and can be re-entered by re-sourcing
    the activate file.
    
    To automatically manage virtual environments, consider using pipx (from the
    pipx package).

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

Let me know your thoughts.

Meanwhile, I'll look if I can reproduce the issue with another custom schema I can share with you, so you can reproduce it.

Kind Regards,
Adrián.

**Comment by dnknth** [comment]
Hello @adrianparilli,

Now this is rather weird because the `mailboxUser` object class shown in the image of my last comment is defined in a custom schema, and it is editable in the most recent version:

<img width="469" alt="Bildschirmfoto 2024-02-11 um 11 54 06" src="https://github.com/dnknth/ldap-ui/assets/41536869/0f7a6170-0707-4d84-b2ee-19169579f0a6">

My test setup uses OpenLdap 2.6.6 on Alpine, and I doubt that the minor version change makes a difference.
Have you checked for messages in the Browser console while an entry with custom attributes is shown in the editor?

My best guess right now is that the UI has trouble with the `x-*` naming scheme, which might trigger some JS error. If that is not the case, please also check the Docker logs of the `ldap-ui` container for exceptions in the Python middleware. 

Alternatively, if you can share the schema, I could test it locally.

**Comment by dnknth** [comment]
Got it reproduced locally without any error messages, neither in the JS console nor in the container logs. It appears to be caused by the `x-*` naming as suspected. Will investigate.

**Comment by dnknth** [comment]
Hello @adrianparilli,

Found the bug, hopefully fixed it and pushed a new amd64 image with hash 283aae683a13. Please try it out.

**Comment by dnknth** [comment]
Damn, found another one. New Docker image hash is 5a2528281e07.

**Comment by dnknth** [comment]
Hey @adrianparilli,

Following up on your issue, I improved the UI for boolean attributes in #52 a little. Feedback appreciated, new Docker images are available.
