### ISSUE TITLE
I can't see any of OU nor entries of OU

### ISSUE THREAD

**Issue by ondrejneufinger** [dnknth/ldap-ui#54]
Hello,

we have one level dn (dc=zajezdy). I can successfully bind to ldap server, but tree is empty and when I click on the rootDn there si error in UI:
"Internal Server Error: The entry cn=subschema specified as the search base does not exist in the Directory Server: No such object"

in logs:
"GET /api/schema 1.1" 500

and later exception:
[2024-03-20 08:56:55,116] ERROR in app: Exception on request GET /api/entry/o=Zajezdy
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/quart/app.py", line 1376, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/quart/app.py", line 1414, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/quart/app.py", line 1007, in handle_user_exception
    raise error
  File "/usr/lib/python3.11/site-packages/quart/app.py", line 1412, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/quart/app.py", line 1506, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 106, in wrapped_view
    resp = await view(**values)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 120, in wrapped_view
    data = await connected(authenticated(view))(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 46, in wrapped_view
    data = await view(**values)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 77, in wrapped_view
    return await view(**values)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 268, in entry
    return _entry(await unique(request.ldap.search(dn, ldap.SCOPE_BASE)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 206, in _entry
    must_attrs, _may_attrs = app.schema.attribute_types(ocs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attribute_types'

I tried with undefined SCHEMA_DN, but it doesn't work.

Is there any solution how to solve it?
(Sorry for my english)

Thanks for your help.

**Comment by dnknth** [comment]
Hello @ondrejneufinger,

Looks like your LDAP server does not reveal the schema under 'cn=subschema'. Is it an OpenLDAP server and do the ACLs let the authenticated user access the schema? The equivalent command line query would be

    ldapsearch -H <LDAP_URL> -D <USER_DN> -x -W -b cn=subschema -s base '+'

Without the schema, the UI won't work, so if the query above does not produce results, you're probably out of luck.

**Comment by ondrejneufinger** [comment]
I connect to our OpenLDAP OpenDJ server, through Apache Directory Studio and found that schemas are under cn=schema (entry subSchemaSubentry).
But I changed SCHEMA_DN to 'cn=schema', the error vanished, but still I see only root DN, nothing else. When I click on "Schema" I see long list of schemas, it should be ok?

Maybe SCHEMA_DN should be also in ENV variable?

Thanks for your help.

**Comment by dnknth** [comment]
Sure, `SCHEMA_DN` is now also pulled from the environment. Docker images are not updated yet.
Have you also checked the browser console for errors?

**Comment by dnknth** [comment]
Hello @ondrejneufinger, 

Your one-level base DN `dc=zajezdy` should not cause any issues. I shortened the base DN of my Flintstones [LDAP demo](https://github.com/dnknth/ldap-demo) to `dc=flintstones` and loaded it into `ldap-ui` without any problems. So please check the container logs and browser console for something suspicious.

**Comment by ondrejneufinger** [comment]
Hello @dnknth 

In Chrome after click on bind user in console show up this error:
TypeError: Cannot set properties of undefined (setting 'subordinates')
    at c (index-37fb71fe.js:17:56396)
    at async index-37fb71fe.js:17:55980

I tried also FF, where i don't have any extensions, but there show me error only on clik to bind user:
TypeError: p is undefined
    c http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:17
    setup http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:17
    ct http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Ve http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    $ http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Ys http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Q http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    k http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    run http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:9
    update http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    y http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    le http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    S http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    re http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    fe http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    j http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    S http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    k http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    run http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:9
    update http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    ct http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    nr http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    promise callback*er http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    As http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    effect http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    xs http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:9
    Fo http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:9
    bn http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:9
    set value http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:9
    2 http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:18
    ct http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Ve http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Tl http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    2 http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:17
    ct http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Ve http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Tl http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    0 http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:17
    ct http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Ve http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    n http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:17
    _t http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:17
    Wi http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:17
    Zi http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:17
    V http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    j http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    S http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    k http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    run http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:9
    update http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    x http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    T http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
[index-37fb71fe.js:13:592](http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js)
    $l http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Ln http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Ve http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    (Async: promise callback)
    Ve http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    $ http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Ys http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Q http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    k http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    run http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:9
    update http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    y http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    le http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    S http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    re http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    fe http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    j http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    S http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    k http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    run http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:9
    update http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    ct http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    nr http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    (Async: promise callback)
    er http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    As http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    effect http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    xs http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:9
    Fo http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:9
    bn http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:9
    set value http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:9
    2 http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:18
    ct http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Ve http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Tl http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    2 http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:17
    ct http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Ve http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Tl http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    0 http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:17
    ct http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    Ve http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    n http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:17
    (Async: EventListener.handleEvent)
    _t http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:17
    Wi http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:17
    Zi http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:17
    V http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    j http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    S http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    k http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    run http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:9
    update http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    x http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13
    T http://ldapadmin.zajezdy.it:8005/assets/index-37fb71fe.js:13

docker logs show me, this:

GET /api/entry/o=Zajezdy 1.1
GET /api/tree/cn=Root DNs,cn=config 1.1

and 

GET /api/entry/cn=Directory Manager,cn=Root DNs,cn=config 1.1

All 200. But what i don't understand, is "cn=root DNs, cn=config". What does it mean?

Thanks for your help

**Comment by dnknth** [comment]
This did not come from `ldap-ui`. Maybe Apache DS?

**Comment by dnknth** [comment]
Where did this funny DN come from? Could you please share your configuration?

**Comment by ondrejneufinger** [comment]
@dnknth I'm sorry, but what configuration, docker?:

```
  ldapuitr:
    image: ldapui:2.1.4
    ports:
      - 8005:5000
    environment:
      - LDAP_URL=ldap://ldap.server.it
      - BASE_DN=o=zajezdy
      - LOGIN_ATTR=cn
      - BIND_DN=cn=Directory Manager
      - BIND_PASSWORD=xxxxxx
```

**Comment by dnknth** [comment]
Well, `BIND_DN` does not appear to be valid, did you mean `BIND_DN=cn=Directory Manager,dc=zajezdy`? Or maybe `BIND_DN=cn=Directory Manager,o=zajezdy` since you have a `BASE_DN=o=zajezdy`?

**Comment by ondrejneufinger** [comment]
`BIND_DN=cn=Directory Manager,o=zajezdy`

When I have split
`WITH_OPERATIONAL_ATTRS = ('+',)`
`WITH_OPERATIONAL_ATTRS1 = ('*',)`

The + is for tree and * for schemas, than the whole tree still isn't printed. I think, that must be some misconfiguration in OpenDJ server...
Thank you for your time.

**Comment by dnknth** [comment]
Hello @ondrejneufinger,

What's wrong with `WITH_OPERATIONAL_ATTRS = ('*','+')`?
And does your `BIND_DN` work now? If yes, I would advise not to hard-code it in the settings, but that of course depends on how you otherwise secure access.

**Comment by ondrejneufinger** [comment]
Nothing is wrong with `WITH_OPERATIONAL_ATTRS = ('*','+')`, but from other ldap managers I discovered, that both operational attributes return nothing or return not all records. So I started experiment with theses attributes and in my case is good to have only one operational attribut (in other managers). I thought, that there it will be the same. But I was wrong.

**Comment by ondrejneufinger** [comment]
Hello @dnknth , yes it is solved. Can be closed. Thank you.
