### ISSUE TITLE
tag version of the project (git and docker)

### ISSUE THREAD

**Issue by dolanor** [dnknth/ldap-ui#55]
Hi,

I would like to use your project (instead of phpLDAPadmin), but I wish there was tags in the docker hub so I could make sure I can upgrade it more safely and pin the docker-compose.yml file to a certain version for my https://github.com/dolanor/dsuite project.

**Comment by dnknth** [comment]
Hello @dolanor,

Some progress. I just packaged the app for [PyPi](https://pypi.org/project/ldap-ui/) and it has a version there. If you'd like to pick it up, you could use the Pip [installation](https://github.com/dnknth/ldap-ui?tab=readme-ov-file#pip) method for Docker as in the [Dockerfile](https://github.com/dnknth/ldap-ui/blob/main/Dockerfile).

Hope this helps.

**Comment by Jack-Kingdom** [comment]
Docker still need tags. We need to know what version we used on deploy.

**Comment by dnknth** [comment]
There you [go](https://hub.docker.com/r/dnknth/ldap-ui/tags). Next time @Jack-Kingdom, please introduce yourself like @dolanor did and state who is behind "we". Good manners go a long way...
