### ISSUE TITLE
Manual install?

### ISSUE THREAD

**Issue by mtissington** [dnknth/ldap-ui#57]
I'm a little confused how this runs.
Can I install and run it on nginx and if so how?
Does it need to be in a virtual environment?

Thanks

**Comment by mtissington** [comment]
Hello and thanks for the detailed answer ... thinking about docker (which sounds easier) .. I have my ldap server using a socket, ldapi:/// 
I'm totally new with docker, can I configure the docker image to use host socket for ldap?

**Comment by dnknth** [comment]
You can probably mount the socket (`/run/slapd/ldapi` on Debian) into the `ldap-ui` container, access rights should be no problem as it is world-writable by default. I have not tried it myself, but there are plenty of socket-binding examples for Docker on the internet.

**Comment by dnknth** [comment]
No further activity → closed
