### ISSUE TITLE
User password update (submit button resets the change)

### ISSUE THREAD

**Issue by jvaubourg** [dnknth/ldap-ui#6]
Hi,

When I try to change the password of a user, it works, which is good :). But then, if I click on the Submit button of the user page, the former password is set back.

Last commit id of my version: d84b68172473c6c2cde8c63f5a0d1ce029f98449

Thank you for your work!

**Comment by dnknth** [comment]
@jvaubourg: Good catch. Commit `b72ccbd` should fix it. Please confirm & close if possible.

**Comment by sbadia** [comment]
Hi @dnknth 
Just tested with a3cc438b891d824a957ca76d18fd5b6e683bd052 and it's ok !
Many thanks :-)
