### ISSUE TITLE
Question: Entry creation

### ISSUE THREAD

**Issue by guenhter** [dnknth/ldap-ui#61]
Hi,

first of all thanks for this nice repo. Great work.

This issue is more a question. It is about "Entry creation".
Does that mean new elements in the "tree" like groups or users can be created? If so, I just haven't figured out how to do that...

**Comment by dnknth** [comment]
Hello @guenhter,

Yes of course entries can be created, provided that the logged in user has sufficient privileges in the directory.
To do so, select the parent entry in the tree. The entry title in the center is actually a dropdown menu with an "Add child" option:

<img width="225" alt="image" src="https://github.com/user-attachments/assets/8c58851f-3e99-49e4-9bd8-05e6c0037891">

**Comment by guenhter** [comment]
Oh boy. Super embarrassing that I haven't found that. Thank you for the quick clarification on that.
