### ISSUE TITLE
MemberOf Overlay

### ISSUE THREAD

**Issue by vlp-git** [dnknth/ldap-ui#7]
_I am quite new in openldap env so I may be wrong_

That would be usefull to show memberof result on each cn pages.

**Comment by dnknth** [comment]
Results of some research and a bit of trial & error:

* `memberOf` is a _virtual_ attribute.
* The server only returns it when a client explicitely requests it in searches.
* `ldap-ui` just requests a `null` attribute list, meaning: all attributes.
* Unfortunately, this does not cause the server to transmit `memberOf` attributes.

Now, I am not aware of any way to request specific (virtual) attribute names _plus_ the entire list of all default attributes (as per schema) in a single search. You could fork and add a second search for `memberOf` in `app.py` after line 236, and merge the results, but I'd rather not add any hacks for special cases.
