### ISSUE TITLE
⛔ Operations error: 000004DC: LdapErr: DSID-0C090A5C, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563 

### ISSUE THREAD

**Issue by Hubbitus** [dnknth/ldap-ui#9]
Run with:

```
podman run -d -p 5900:5000 -e LDAP_URL=ldap://epam.com:3268/ -e BASE_DN=dc=epam,dc=com docker.io/dnknth/ldap-ui                                                                                                                             
```
On attempt to login just got such error:
![image](https://user-images.githubusercontent.com/720349/124500431-73be9680-ddc8-11eb-83f6-614c8f88d70f.png)

**Comment by dnknth** [comment]
The error message says it pretty clearly.
As per the Readme:

> The app always requires authentication, even if the directory permits anonymous access. User credentials are validated through a bind on the directory.

The directory at `epam.com` seems not happy either with your credentials, or it requires SASL authentication which is not supported by the `ldap-ui` client.

**Comment by dnknth** [comment]
Updated the README to clarify authentication methods

**Comment by dnknth** [comment]
Were you able to solve the problem?

**Comment by Hubbitus** [comment]
Thank you for the answer.
Using `phpldapadmin` - it asks at the entrance which credentials use. How I should provide them for the `ldap-ui`?

**Comment by dnknth** [comment]
@Hubbitus, please see the updated README. It now has a section on this.
